version: 0.2 
phases: 
  install:
    runtime-versions:
      docker: 18
    commands: 
      - "mvn clean package"
  pre_build: 
    commands: 
      - "echo Logging in to Docker Hub..."
      - docker login -u "saikarthikias" -p "HelloPassword123"

  build: 
    commands: 
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t saikarthikias/springboot-demo-dockerhub ."
      - "docker tag saikarthikias/springboot-demo-dockerhub saikarthikias/springboot-demo:latest"
  post_build: 
    commands: 
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "docker push saikarthikias/springboot-demo:latest"
  